### ISSUE TITLE
单个ViewController中的某个View，不是self.view，横屏显示不是整个屏幕

### ISSUE THREAD

**Issue by sauchye** [newyjp/BLLandscape#3]
Hi，newyjp：
       最近研究一个视图横屏显示， 参考您的``BLLandscape``发现横屏后显示不全（不是整个屏幕），
``单个ViewController中的某个View，不是self.view，横屏显示不是整个屏幕``

如：

* 竖屏显示
<img width="369" alt="jietu20170804-232813 2x" src="https://user-images.githubusercontent.com/4171847/28975542-fe4c2eda-796c-11e7-92f3-9eef023e851e.png">

* 横屏显示
<img width="373" alt="jietu20170804-232826 2x" src="https://user-images.githubusercontent.com/4171847/28975567-0f788df2-796d-11e7-9d2c-2f1ecd05b9fc.png">

**Comment by sauchye** [comment]
![Uploading Jietu20170804-232826@2x.png…](横屏)
![Uploading Jietu20170804-232813@2x.png…](竖屏)

**Comment by sauchye** [comment]
``` 
- (void)buttonAction:(UIButton *)sender{
    sender.selected = !sender.selected;
    if (self.rootView.viewStatus == BLLandscapeViewStatusPortrait) {
        
        [self.rootView bl_landscapeAnimated:YES animations:^{
            self.rootView.frame = self.view.bounds;
            //CGRectMake(0, 0, self.view.bounds.size.height, self.view.bounds.size.width);
            self.button.center  = self.view.center;
        } complete:^{
        }];
    }
    else if (self.rootView.viewStatus == BLLandscapeViewStatusLandscape){
        
        [self.rootView bl_protraitAnimated:YES animations:^{
            self.rootView.frame = CGRectMake(0, 0, self.view.frame.size.width, 300);
            self.button.center  = self.rootView.center;
        } complete:^{
        }];
    }
}

```

**Comment by dito010** [comment]
animations 的回调中不需要再写这句了 self.rootView.frame = self.view.bounds, 这个回调是给其他需要做横屏动画的子控件使用的.

**Comment by sauchye** [comment]
thx~
